### ISSUE TITLE
Reconnect to seeds

### ISSUE THREAD

**Issue by jaekwon** [tendermint/go-p2p#13]
There should be some way for Tendermint to tell go-p2p that some peers are persistent and should be reconnected to.

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/430

**Comment by melekes** [comment]
Looking at the code I see some things which could be improved:

### 1. MConnection stopped twice

in connection.go https://github.com/tendermint/go-p2p/blob/13-reconnect-to-seeds/connection.go#L179
and in peer.go https://github.com/tendermint/go-p2p/blob/13-reconnect-to-seeds/peer.go#L84

### 2. Remove MConnection dependency on go-config

What I propose is to add `MConnectionConfig` struct (this seems to be the way many Go libs handle initialization)

```
type MConnectionConfig struct {
  send_rate int
  recv_rate int
  persistent bool
}
```

**Comment by melekes** [comment]
Ok, there is no easy way to do it because of how it is implemented right now. I see 2 ways:

1) `Peer#persistent` bool property and `PersistentConn`, which can wrap `net.Conn` and have a `Redial()` function

![opt 1](https://cloud.githubusercontent.com/assets/1282182/24742976/819f9538-1abd-11e7-8956-aafee908e336.png)

2) Move all connect logic into Peer, so he could reset connection himself based on `Peer#persistent` property

![opt 2](https://cloud.githubusercontent.com/assets/1282182/24742973/7daa224a-1abd-11e7-950a-1f9cc67f2cd5.png)

**Comment by ebuchman** [comment]
I think the simplest thing for now is just remove the peer and try and add it to the switch anew. See PR #17

**Comment by melekes** [comment]
Impl in https://github.com/tendermint/go-p2p/pull/18
